version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: exampledb
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
